# fly.toml file generated for model-gallery on 2023-04-18T01:22:00+07:00

app = "model-gallery-staging"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "sin"
processes = []

[env]
  ENV = "staging"
  PORT = "8080"
  REACT_APP_BASE_URL = "https://model-gallery-api-staging.onrender.com"
  REACT_APP_PUBLIC_URL = "https://model-gallery-staging.fly.dev"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
